src/Frontend/Models/ErrorViewModel.cs
using System;

namespace Frontend.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Frontend/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Frontend.Models;
using System.Net.Http;

namespace Frontend.Controllers
{
    public class HomeController : Controller
    {
        static readonly string url = "http://localhost:5000/api/values/";

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Upload()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> TextDetails(string id)
        {
            string textDetails = null; 
            HttpClient client = new HttpClient();

            HttpResponseMessage request = await client.GetAsync(url + id);
            textDetails = await request.Content.ReadAsStringAsync();
            string ratio = ParseData(textDetails, 0);
            string region = ParseData(textDetails, 1);
            ViewData["TextDetails"] = ratio;
            ViewData["Region"] = region;
        
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(string data, string region)
        {
            ShowProcess(data, region);
            string id = null; 

            if (data != null)
            {
                HttpClient client = new HttpClient();
                string text = $"{data}:{region}";
                HttpResponseMessage request = await client.PostAsJsonAsync(url, text);
                id = await request.Content.ReadAsStringAsync();
            }         

            return Redirect("TextDetails/" + id);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private static string ParseData( string msg, int pos )
        {
            return msg.Split( ':' )[pos];
        }

        public void ShowProcess(string data, string region)
        {   
            Console.WriteLine("Data: " + data);
            Console.WriteLine("Region: " + region);
            Console.WriteLine("----------------------------------------");
        }
    }
}

src/Frontend/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Frontend.Models;
using System.Net.Http;

namespace Frontend.Controllers
{
    public class StatisticsController : Controller
    {
        static readonly string url = "http://localhost:5000/api/statistics/{0}";

        [HttpGet]
        public async Task<IActionResult> TextStatistics()
        {
            string textStatistics = null; 
            HttpClient client = new HttpClient();
            string tail = "TextRankCalculated";
            HttpResponseMessage request = await client.GetAsync(String.Format(url, tail));
            textStatistics = await request.Content.ReadAsStringAsync();

            string textNum = ParseData(textStatistics, 0);
            string highRankPart = ParseData(textStatistics, 1);
            string avgRank = ParseData(textStatistics, 2);

            ViewData["TextNum"] = textNum;
            ViewData["HighRankPart"] = highRankPart;
            ViewData["AvgRank"] = avgRank;
        
            return View();
        }

        private static string ParseData( string msg, int pos )
        {
            return msg.Split( ':' )[pos];
        }
    }
}

src/Frontend/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h2>Описание</h2>

    <p>
        Необходимо разработать приложение, состоящее из двух компонентов: Frontend и Backend, взаимодействующих по протоколу HTTP.        
    </p>
</div>

src/Frontend/Views/Home/TextDetails.cshtml
@{
    ViewData["Title"] = "Text details";
}

<div>
    <p>
        Отношение: @(ViewData["TextDetails"])           
    </p>
    <p>
        Регион: @(ViewData["Region"])           
    </p>
</div>

src/Frontend/Views/Home/Upload.cshtml
@{
    ViewData["Title"] = "Data input";
}
<div>
    <h2>Форма ввода</h2>
    <form method="post">
        Data: <input name="data" type="text"/>
        <select name="region">
            <option value="rus">RUS - Россия</option>
            <option value="eu">EU - Европейский Союз</option>
            <option value="usa">USA - США</option>
        </select>
        <br>
        <input type="submit">
    </form>
</div>

src/Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Frontend</title>
</head>
<body>
    <nav>
        <ul>
            <li><a asp-area="" asp-controller="Home" asp-action="Index">Главная</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Upload">Форма ввода</a></li>
            <li><a asp-area="" asp-controller="Statistics" asp-action="TextStatistics">Cтатистика</a></li>
        </ul>
    </nav>
    <div class="container body-content">
        <h1>Задание #7 Материализованное представление (Materialized View)</h1>
        @RenderBody()
        <hr/>
        <footer>
            Студент: Москвичев Михаил, ПС-32
        </footer>
    </div>
</body>
</html>

src/Frontend/Views/Statistics/TextStatistics.cshtml
@{
    ViewData["Title"] = "Text statistics";
}

<div>
    <p>
        Общее количество всех обработанных текстов: @(ViewData["TextNum"])           
    </p>
    <p>
        Количество текстов с высокой оценкой (выше 0.5): @(ViewData["HighRankPart"])           
    </p>
    <p>
        Средняя оценка: @(ViewData["AvgRank"])           
    </p>
</div>